### ISSUE TITLE
GET Groups : list response does not include users [userInfo]

### ISSUE THREAD

**Issue by georgi-butev** [docusign/code-examples-powershell#13]
Hello,

When I run the following code I get the DocuSign groups as expected. However I don't get the users in the group. In the API reference there is users [userInfo] part of the group object. Can I get the list of groups including the list of users or is this a limitation of the PowerShell implementation? I could use GroupUsers:list as well but then I would have to iterate for each group id from Groups:list which is not ideal.

`$response = $(Invoke-RestMethod  `
    -Uri "${apiUri}/v2.1/accounts/${accountId}/groups/" `
    -Method 'GET' `
    -Headers @{
      'Authorization' = "Bearer $accessToken";
      'Content-Type'  = "application/json";
    }`
).groups`

Thank you.

**Comment by EdwinMoralesDS** [comment]
Hello @georgi-butev , Thank you for reporting this issue. I did a few test with the API and I have the same behavior you described. I'm not sure if this is a problem with the documentation or if it is a problem with the API response. We have created bug number EC-3947 so the engineering team can take a look at this. 

I recommend you contact your account team so they can add your account to the bug. They should also be able to update you on the status of this bug

**Comment by georgi-butev** [comment]
Thank you @EdwinMoralesDS 
I think if we can get the API updated with the following similar to [signing_groups](https://developers.docusign.com/docs/esign-rest-api/reference/signinggroups/signinggroups/list/) that would be useful:
`<html>
<body>


include_users | string | When set to true, the response includes the signing group members.
-- | -- | --



</body>
</html>`

**Comment by InbarGazit** [comment]
The product team building the API for this endpoint is not willing to commit to make this update at this time. Closing, as it's not related directly to the code examples in here.
